filetype off 
call pathogen#infect()

call l9#defineVariableDefault('g:fuf_buffertag_ctagsPath'  , 'pctags')
filetype plugin indent on
let mapleader = ","
set tags+=~/Sites/tags
" FuzzyFinder Keymaps
nnoremap ,f :FufFile **/<CR>
nnoremap ,t :FufBufferTag <CR>
nnoremap ,b :FufBuffer <CR>
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk
"nnoremap <Down> gj
"nnoremap <Up> gk
"vnoremap <Down> gj
"vnoremap <Up> gk
"inoremap <Down> <C-o>gj
"inoremap <Up> <C-o>gk

" DRUPAL
if has("autocmd")
  " Drupal *.module and *.install files.
  augroup module
    autocmd BufRead,BufNewFile *.module set filetype=php
    autocmd BufRead,BufNewFile *.install set filetype=php
    autocmd BufRead,BufNewFile *.test set filetype=php
    autocmd BufNewFile,BufRead *.less set filetype=less
    autocmd BufRead,BufNewFile *.css3 set filetype=css
    autocmd FileType python set omnifunc=pythoncomplete#Complete
    autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
    autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
    autocmd FileType css set omnifunc=csscomplete#CompleteCSS
    autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
    autocmd FileType php set omnifunc=phpcomplete#CompletePHP
    autocmd FileType c set omnifunc=ccomplete#Complete
  augroup END
endif
syntax on
" colorscheme and font
"let molokai_original=1
"colorscheme molokai
colorscheme solarized
set background=light
set gfn=Consolas:h14
" add directories for ctags
" set tags+=tags;$HOME/Sites
set guioptions-=T
set guioptions-=r
set guioptions-=l
set guioptions-=R
set guioptions-=L
set guioptions-=b
set guioptions-=e
set wrap
set linebreak
set nolist
set formatoptions+=1
set tabstop=2
set shiftwidth=2
set number
set autoindent
set smartindent
set sm
set expandtab
set hlsearch
set incsearch
set ruler
set noswapfile
"set cursorline
" more powerful backspacing
set backspace=indent,eol,start
" syntaxhighlighting
set backupdir=~/.vimbackups
set directory=~/.vimswaps
" lazy method of appending this onto your .vimrc ":w! >> ~/.vimrc"
" ------------------------------------------------------------------
" this block of commands has been autogenerated by solarized.vim and
" includes the current, non-default Solarized option values.
" To use, place these commands in your .vimrc file (replacing any
" existing colorscheme commands). See also ":help solarized"

" ------------------------------------------------------------------
" Solarized Colorscheme Config
" ------------------------------------------------------------------
let g:solarized_contrast="high"    "default value is normal
let g:solarized_visibility="high"    "default value is normal
let g:solarized_diffmode="high"    "default value is normal
let g:solarized_hitrail=1    "default value is 0
syntax enable
set background=light
colorscheme solarized
" ------------------------------------------------------------------

" The following items are available options, but do not need to be
" included in your .vimrc as they are currently set to their defaults.

" let g:solarized_termtrans=0
" let g:solarized_degrade=0
" let g:solarized_bold=1
" let g:solarized_underline=1
" let g:solarized_italic=1
" let g:solarized_termcolors=16
" let g:solarized_menu=1

